// src/service-worker.js – custom Service Worker for PWA
// This file is used by vite-plugin-pwa (imported automatically).

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { Queue } from 'workbox-background-sync';

// Pre‑cache all assets generated by Vite (the __WB_MANIFEST placeholder is injected at build time)
precacheAndRoute(self.__WB_MANIFEST || []);

// ------------------------------------------------------------
// Runtime caching for API requests – Stale‑while‑revalidate strategy
// ------------------------------------------------------------
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/'),
    new StaleWhileRevalidate({
        cacheName: 'api-cache',
        plugins: [],
    })
);

// ------------------------------------------------------------
// Background Sync – queue for POST requests made while offline
// ------------------------------------------------------------
const bgSyncQueue = new Queue('post-requests-queue', {
    maxRetentionTime: 24 * 60, // Retry for up to 24 hours
});

self.addEventListener('fetch', (event) => {
    const { request } = event;
    // Only handle POST requests to our API (e.g., contact form)
    if (request.method === 'POST' && request.url.includes('/api/')) {
        const clone = request.clone();
        event.waitUntil(
            bgSyncQueue.pushRequest({ request: clone }).catch(() => {
                // If push fails, we simply let the request fail – it will be retried later
            })
        );
        // Respond with a generic acknowledgment so the UI can show an offline toast
        event.respondWith(
            new Response(JSON.stringify({ success: true, offline: true }), {
                headers: { 'Content-Type': 'application/json' },
            })
        );
    }
});

// Optional: listen to sync event (fallback for browsers that support SyncManager)
self.addEventListener('sync', (event) => {
    if (event.tag === 'post-requests-queue') {
        event.waitUntil(bgSyncQueue.replayRequests());
    }
});
